# Generated by Django 3.0.3 on 2020-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('estacion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'bicicleta',
                'verbose_name_plural': 'bicicletas',
            },
        ),
    ]
