# Generated by Django 3.0.3 on 2020-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField()),
                ('rut', models.CharField(max_length=18)),
                ('fecha_nac', models.DateField()),
                ('tarjeta', models.CharField(max_length=35)),
                ('domicilio', models.CharField(max_length=31)),
                ('comuna', models.CharField(max_length=31)),
                ('genero', models.CharField(max_length=10)),
                ('tipo_relacion', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField()),
                ('email_corporativo', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
