# Generated by Django 3.0.3 on 2020-10-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0002_auto_20201020_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(choices=[('RE', 'Comuna la reina'), ('PRO', 'Comuna providencia'), ('FL', 'Comuna la florida')], default='RE', max_length=31),
        ),
    ]
